version: "3.6"

services:
  # Frontend App
  frontend:
    container_name: ${PROJECT_NAME}-frontend
    image: node:lts-alpine3.18
    env_file:
      - ./.env
    ports:
      - "${HOST}:${FRONT_DEV_PORT}:${FRONT_DEV_PORT}"
      - "${HOST}:${FRONT_PROD_PORT}:${FRONT_PROD_PORT}"
    command: sh -c "tail -f /dev/null"
    volumes:
      - ./frontend:/var/www/html
    restart: unless-stopped
    working_dir: /var/www/html

  # Backend API
  backend:
    container_name: ${PROJECT_NAME}-backend
    image: node:lts-alpine3.18
    env_file:
      - ./.env
    ports:
      - "${HOST}:${BACK_PORT}:${BACK_PORT}"
    command: sh -c "tail -f /dev/null"
    volumes:
      - ./backend:/var/www/html
    networks:
      - dbnetwork
    restart: unless-stopped
    working_dir: /var/www/html

  # Database
  database:
    container_name: ${PROJECT_NAME}-database
    image: mongo:latest
    env_file:
      - ./.env
    volumes:
      - ./database/DB:/data/db
    networks:
      - dbnetwork
networks:
  dbnetwork:
    driver: bridge
